#!/bin/bash

theme="iceberg"

rofi -show drun \
-display-drun "Search " \
-hide-scrollbar true \
-bw 2 \
-lines 22 \
-padding 36 \
-xoffset 20 \
-yoffset -45 \
-width 24 \
-location 7\
-columns 1 \
-font "JetBrainsMono Nerd Font 11" \
-theme $HOME/.config/rofi/themes/$theme/default.rasi
