#! /bin/sh

## autostart
lxqt-session &
lxqt-powermanagement &
# dunst &
# lxqt-policykit-agent &
/usr/lib/polkit-kde-authentication-agent-1 &
picom --experimental-backend &
blueman-applet &
kmix &
kdeconnect-indicator &
parcellite &
nitrogen --restore &
numlockx &
xsetroot -cursor_name arrow &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
./.config/polybar/launch.sh &
# sxhkd &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

## border config
bspc config border_width        3
bspc config window_gap          10
bspc config top_padding         30
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## coloring
bspc config normal_border_color		      "#282c34"
bspc config active_border_color	          "#131613"
bspc config focused_border_color	      "#abb2bf"
bspc config presel_feedback_color	      "#56b6c2"
bspc config urgent_border_color 	      "#e06c75"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating
bspc rule -a Kvantum\ Manager state=floating
bspc rule -a Volume\ Control state=floating
bspc rule -a lxqt-config state=floating
bspc rule -a qt5ct state=floating
