#! /bin/sh

## autostart
lxqt-session &
lxqt-powermanagement &
dunst &
lxqt-policykit-agent &
picom --experimental-backend &
blueman-applet &
kmix &
kdeconnect-indicator &
parcellite &
nitrogen --restore &
numlockx &
xsetroot -cursor_name arrow
./.config/polybar/BSPWM.sh &
# sxhkd &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

## border config
bspc config border_width        3
bspc config window_gap          10
bspc config top_padding         0
bspc config bottom_padding      30
bspc config left_padding        0
bspc config right_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## coloring
# dracula
bspc config normal_border_color		      "#44475a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#f8f8f2"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"
# iceberg
# bspc config normal_border_color		      "#8389a3"
# bspc config active_border_color	          "#dcdfe7"
# bspc config focused_border_color	      "#262a3f"
# bspc config presel_feedback_color	      "#327698"
# bspc config urgent_border_color 	      "#cc517a"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating
bspc rule -a Kvantum\ Manager state=floating
bspc rule -a Volume\ Control state=floating
bspc rule -a lxqt-config state=floating
bspc rule -a qt5ct state=floating
