#! /bin/sh

## autostart
mpd &
lxqt-config-monitor -l &
light-locker-command -i &
lxqt-session &
lxqt-powermanagement &
/usr/lib/polkit-kde-authentication-agent-1 &
picom --experimental-backend &
blueman-applet &
kdeconnect-indicator &
parcellite &
nitrogen --restore &
numlockx &
xsetroot -cursor_name arrow &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
./.config/polybar/launch.sh &

export _JAVA_AWT_WM_NONREPARENTING=1
export wm="bpwm"

pgrep -x sxhkd > /dev/null || sxhkd &

# monitor config
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "3" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III
  bspc monitor $(bspc query -M | sed -n 2p) -d IV V VI
  bspc monitor $(bspc query -M | sed -n 3p) -d VII VIII IX
elif [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV
  bspc monitor $(bspc query -M | sed -n 2p) -d V VI VII VIII
else
  bspc monitor -d I II III IV V VI 
fi

## border config
bspc config border_width        2
bspc config window_gap          10
bspc config top_padding         0
bspc config bottom_padding      30
bspc config left_padding        0
bspc config right_padding       0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## coloring
bspc config normal_border_color		      "#292d3e"
bspc config active_border_color	          "#131613"
bspc config focused_border_color	      "#eeffff"
bspc config presel_feedback_color	      "#89ddff"
bspc config urgent_border_color 	      "#f07178"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating
bspc rule -a Kvantum\ Manager state=floating
bspc rule -a Volume\ Control state=floating
bspc rule -a lxqt-config state=floating
bspc rule -a qt5ct state=floating
